<link 
  rel="preconnect" 
  href="https://fonts.googleapis.com">
<link 
  rel="preconnect" 
  href="https://fonts.gstatic.com" 
  crossorigin>
<link 
  href="https://fonts.googleapis.com/css2?family=Assistant:wght@200;300;400;500;600;700;800&display=swap" 
  rel="stylesheet">
<link 
  rel="icon" 
  type="image/x-icon" 
  href="/image/favicon.ico">
<link 
  rel="stylesheet" 
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link 
  rel="stylesheet" 
  href="/css/app.css">
<link 
  rel="stylesheet" 
  href="/css/components/header.css">